#!/usr/bin/env python3
"""Regenerate the tested-version constraints in ``constraints/``.

pyproject.toml DECLARES dependencies (ranges); ``constraints/*.txt`` PINS the
versions a fresh ``install.py`` gets by default, so tracking output does not
change whenever an upstream package releases. Bump deliberately:

    python tools/lock_constraints.py                       # re-resolve, keep pins
    python tools/lock_constraints.py --upgrade-package numpy
    python tools/lock_constraints.py --upgrade             # everything to latest

then re-run the equivalence gates (tools/equivalence/env_swap_gate.sh) on MPS
and CUDA before committing the new pins.

Files (uv ``--universal``: one file covers Linux, macOS and Windows, py3.11+):
  constraints/base.txt    every tier: core + cpu/mps extras + sam + dev + docs
  constraints/cuda12.txt  added on CUDA 12 hosts (ORT GPU <1.27, cupy/TensorRT cu12)
  constraints/cuda13.txt  added on CUDA 13 hosts

torch/torchvision and their nvidia-*/triton dependencies are deliberately NOT
pinned here: install.py installs them from the PyTorch wheel index for the
tier (``TORCH_VERSION``), and the nvidia wheels must follow that build.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "constraints"

#: Never pinned here (see module docstring).
EXCLUDE = re.compile(r"^(torch|torchvision|triton|nvidia-|cuda-|hydra-suite)", re.I)

BASE_EXTRAS = ["cpu", "mps", "sam", "dev", "docs"]


def _compile(
    extras: list[str], seeds: list[Path], args: argparse.Namespace
) -> list[str]:
    cmd = [
        "uv",
        "pip",
        "compile",
        str(REPO / "pyproject.toml"),
        "--universal",
        "--python-version",
        "3.11",
        "--no-header",
        "--no-annotate",
        "--quiet",
        # TensorRT's PyPI entries are stubs that fetch from NVIDIA's index;
        # resolving their metadata off-Linux needs the real index.
        "--extra-index-url",
        "https://pypi.nvidia.com",
        "--index-strategy",
        "unsafe-best-match",
    ]
    for extra in extras:
        cmd += ["--extra", extra]
    for seed in seeds:
        if seed.exists():
            cmd += ["--constraint", str(seed)]
    if args.upgrade:
        cmd.append("--upgrade")
    for pkg in args.upgrade_package:
        cmd += ["--upgrade-package", pkg]
    out = subprocess.run(cmd, check=True, capture_output=True, text=True).stdout
    return [ln for ln in out.splitlines() if ln.strip() and not EXCLUDE.match(ln)]


def _write(name: str, lines: list[str], note: str) -> None:
    header = [
        f"# {note}",
        "# GENERATED by tools/lock_constraints.py -- do not edit by hand.",
        "# Bump deliberately, then re-run the equivalence gates.",
    ]
    (OUT / name).write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    print(f"wrote constraints/{name}: {len(lines)} pins")


def main(argv=None) -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--upgrade", action="store_true")
    p.add_argument("--upgrade-package", action="append", default=[])
    p.add_argument(
        "--seed",
        action="append",
        type=Path,
        default=[],
        help="extra constraint file to seed versions from (e.g. a pip freeze)",
    )
    args = p.parse_args(argv)
    OUT.mkdir(exist_ok=True)

    base_seeds = [OUT / "base.txt", *args.seed]
    base = _compile(BASE_EXTRAS, base_seeds, args)
    _write(
        "base.txt",
        base,
        "Tested pins for every tier (core + cpu/mps + sam + dev + docs).",
    )

    with tempfile.TemporaryDirectory() as tmp:
        base_file = Path(tmp) / "base.txt"
        base_file.write_text("\n".join(base) + "\n")
        base_names = {re.split(r"[=<>; ]", ln, maxsplit=1)[0].lower() for ln in base}
        for major in (12, 13):
            name = f"cuda{major}.txt"
            pins = _compile(
                ["cuda" + str(major), "sam"], [base_file, OUT / name, *args.seed], args
            )
            extra = [
                ln
                for ln in pins
                if re.split(r"[=<>; ]", ln, maxsplit=1)[0].lower() not in base_names
            ]
            _write(
                name,
                extra,
                f"Tested pins added on CUDA {major} hosts (on top of base.txt).",
            )
    return 0


if __name__ == "__main__":
    sys.exit(main())
